Nomenclatura correcta lecturas
devfmx/cinta-blanca pull request #9
Opened 2019-08-26 18:41 UTC by gerardomdn95

Creo que este Pull request es necesario porque las lecturas están nombradas de manera incorrecta.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devfmx/cinta-blanca/9)

2019-08-26 19:16 UTC, LigorioSalgado approved these changes

2019-08-26 19:16 UTC, LigorioSalgado commented on 1.4 Reto flexbox/index.html
> +  <div class="costa-rica">
@gerardomdn95 Agregaste un ejercicio para los de costa rica ??

2019-08-26 20:15 UTC, gerardomdn commented on 1.4 Reto flexbox/index.html
> +  <div class="costa-rica">
Sí, pero no recordaba que lo hice en este mismo branch.

También funcionó para explicar Flexbox, ahora lo borro @LigorioSalgado

2019-08-26 20:58 UTC, Dagorik requested changes

2019-08-26 20:58 UTC, Dagorik commented on 1.4 Reto flexbox/index.html
> +  <div class="costa-rica">
Quitar lo de cotarrica x2

2019-08-27 17:55 UTC, gerardomdn95 commented
@LigorioSalgado @Dagorik Ya eliminé lo de Costa Rica

2019-08-27 22:49 UTC, LigorioSalgado approved these changes

2019-09-02 21:04 UTC, Masavi approved these changes

2019-09-03 00:01 UTC, Dagorik approved these changes

2019-09-03 00:01 UTC, merged